lang: nl
timezone: Europe/Amsterdam

title: Leermiddelenoverzicht
description: Een overzicht van mijn samenvattingen en andere leermiddelen

email: gijs6@dupunkto.org
github_username: gijs6

domain: school.gijs6.nl
url: https://school.gijs6.nl
permalink: /:path/:basename

markdown: kramdown
kramdown:
    input: GFM
    math_engine: mathjax
    syntax_highlighter_opts:
        disable: true

plugins:
    - "jekyll-github-metadata"

exclude:
    - .git/
    - _data/
    - _scripts/
    - README.md
    - Gemfile
    - LICENSE
    - .gitignore
    - vendor
    - additional
