#!/bin/bash

serve() {
  .venv/bin/python binder.py serve
}

build() {
  .venv/bin/python binder.py build
}

format() {
  ruff format .
  prettier --write "**/*.{css,js}"
  prettier --write "**/*.{json,xml,yml}"
  djlint . --reformat
  markdownlint --fix "**/*.md" || true
}
