#!/bin/bash

serve() {
  .venv/bin/python binder.py serve --dev
}

build() {
  .venv/bin/python binder.py build
}

deploy() {
  build
  npx prettier --write --ignore-path /dev/null "build/**/*.{css,js,xml,html}"
  lift deploy && echo "Deployed successfully to https://$(yq .name Liftfile)"
}

format() {
  ruff format .
  npx prettier --write "**/*.{css,js}"
  npx prettier --write "**/*.{json,xml}"
  djlint . --reformat
}
