#!/bin/bash

export FORMAT_HTML=1

serve() {
  .venv/bin/python -m composer serve --dev
}

build() {
  .venv/bin/python -m composer build
  lightningcss --bundle --minify --browserslist build/assets/styles/main.css -o build/assets/styles/main.css
}

deploy() {
  build
  prettier --write --ignore-path /dev/null "build/**/*.{css,js,xml,html}"
  shake_super deploy
}
